const toneMap: Record<string, Record<number, string>> = {
  'a': { 1: 'ā', 2: 'á', 3: 'ǎ', 4: 'à' },
  'e': { 1: 'ē', 2: 'é', 3: 'ě', 4: 'è' },
  'i': { 1: 'ī', 2: 'í', 3: 'ǐ', 4: 'ì' },
  'o': { 1: 'ō', 2: 'ó', 3: 'ǒ', 4: 'ò' },
  'u': { 1: 'ū', 2: 'ú', 3: 'ǔ', 4: 'ù' },
  'v': { 1: 'ǖ', 2: 'ǘ', 3: 'ǚ', 4: 'ǜ' },
  'ai': { 1: 'āi', 2: 'ái', 3: 'ǎi', 4: 'ài' },
  'ei': { 1: 'ēi', 2: 'éi', 3: 'ěi', 4: 'èi' },
  'ao': { 1: 'āo', 2: 'áo', 3: 'ǎo', 4: 'ào' },
  'ou': { 1: 'ōu', 2: 'óu', 3: 'ǒu', 4: 'òu' },
  'an': { 1: 'ān', 2: 'án', 3: 'ǎn', 4: 'àn' },
  'en': { 1: 'ēn', 2: 'én', 3: 'ěn', 4: 'èn' },
  'in': { 1: 'īn', 2: 'ín', 3: 'ǐn', 4: 'ìn' },
  'un': { 1: 'ūn', 2: 'ún', 3: 'ǔn', 4: 'ùn' },
  'ang': { 1: 'āng', 2: 'áng', 3: 'ǎng', 4: 'àng' },
  'eng': { 1: 'ēng', 2: 'éng', 3: 'ěng', 4: 'èng' },
  'ing': { 1: 'īng', 2: 'íng', 3: 'ǐng', 4: 'ìng' },
  'ong': { 1: 'ōng', 2: 'óng', 3: 'ǒng', 4: 'òng' },
};

const vowels = ['ai', 'ei', 'ao', 'ou', 'an', 'en', 'in', 'un', 'ang', 'eng', 'ing', 'ong', 'a', 'e', 'i', 'o', 'u', 'v'];

function addTone(pinyin: string, tone: number): string {
  for (const vowel of vowels) {
    const index = pinyin.indexOf(vowel);
    if (index !== -1) {
      const replacement = toneMap[vowel][tone] || vowel;
      return pinyin.slice(0, index) + replacement + pinyin.slice(index + vowel.length);
    }
  }
  return pinyin;
}

export const PinyinTones: Record<string, string> = {
  '一': 'yī',
  '二': 'èr',
  '三': 'sān',
  '人': 'rén',
  '口': 'kǒu',
  '手': 'shǒu',
  '水': 'shuǐ',
  '火': 'huǒ',
  '山': 'shān',
  '石': 'shí',
  '田': 'tián',
  '云': 'yún',
  '雨': 'yǔ',
  '日': 'rì',
  '月': 'yuè',
  '木': 'mù',
  '禾': 'hé',
  '上': 'shàng',
  '下': 'xià',
  '大': 'dà',
  '小': 'xiǎo',
  '多': 'duō',
  '少': 'shǎo',
  '天': 'tiān',
  '土': 'tǔ',
  '目': 'mù',
  '耳': 'ěr',
  '足': 'zú',
  '中': 'zhōng',
  '家': 'jiā',
  '爸': 'bà',
  '妈': 'mā',
  '爷': 'yé',
  '奶': 'nǎi',
  '哥': 'gē',
  '姐': 'jiě',
  '弟': 'dì',
  '妹': 'mèi',
  '花': 'huā',
  '草': 'cǎo',
  '树': 'shù',
  '林': 'lín',
  '鸟': 'niǎo',
  '鱼': 'yú',
  '春': 'chūn',
  '夏': 'xià',
  '爱': 'ài',
  '国': 'guó',
  '学': 'xué',
  '书': 'shū',
  '风': 'fēng',
  '雪': 'xuě',
  '电': 'diàn',
  '狗': 'gǒu',
  '猫': 'māo',
  '虫': 'chóng',
  '蜂': 'fēng',
  '蝴': 'hú',
  '蝶': 'dié',
  '马': 'mǎ',
  '牛': 'niú',
  '羊': 'yáng',
  '兔': 'tù',
  '河': 'hé',
  '海': 'hǎi',
  '沙': 'shā',
  '冬': 'dōng',
  '秋': 'qiū',
  '星': 'xīng',
  '光': 'guāng',
  '虾': 'xiā',
  '蟹': 'xiè',
  '蛙': 'wā',
  '蛇': 'shé',
  '龟': 'guī',
  '象': 'xiàng',
  '熊': 'xióng',
  '鹿': 'lù',
  '叶': 'yè',
  '笑': 'xiào',
  '哭': 'kū',
  '跑': 'pǎo',
  '跳': 'tiào',
  '吃': 'chī',
  '喝': 'hē',
  '睡': 'shuì',
  '醒': 'xǐng',
  '快': 'kuài',
  '慢': 'màn',
  '高': 'gāo',
  '矮': 'ǎi',
  '长': 'cháng',
  '短': 'duǎn',
  '远': 'yuǎn',
  '近': 'jìn',
  '新': 'xīn',
  '老': 'lǎo',
  '走': 'zǒu',
  '飞': 'fēi',
  '游': 'yóu',
  '唱': 'chàng',
  '做': 'zuò',
  '写': 'xiě',
  '读': 'dú',
  '说': 'shuō',
  '听': 'tīng',
  '看': 'kàn',
  '想': 'xiǎng',
};

export function getTonePinyin(char: string): string {
  return PinyinTones[char] || '';
}
